// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.mongo.userstore {
    exports com.mastfrog.acteur.mongo.userstore;

    // Transitive detected by source scan
    requires com.mastfrog.acteur;

    // Sibling com.mastfrog/acteur-auth-3.0.0-dev
    requires com.mastfrog.acteur.auth;

    // Sibling com.mastfrog/acteur-mongo-3.0.0-dev
    requires com.mastfrog.acteur.mongo;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.time;

    // Sibling com.mastfrog/url-3.0.0-dev
    requires com.mastfrog.url;

    // Inferred from test-source-scan
    requires transitive junit;

}
