// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.auth {
    exports com.mastfrog.acteur.auth;

    // Sibling com.mastfrog/acteur-3.0.0-dev
    requires com.mastfrog.acteur;

    // Transitive detected by source scan
    requires com.mastfrog.acteur.deprecated;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Inferred from source scan
    requires com.mastfrog.misc;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.time;

    // Inferred from test-source-scan
    requires transitive junit;

}
