open module com.mastfrog.acteur.facebook.auth {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.facebook.auth;

    // derived from com.google.http-client/google-http-client-jackson2-1.41.7 in com/google/http-client/google-http-client-jackson2/1.41.7/google-http-client-jackson2-1.41.7.pom
    requires transitive com.google.http.client.google.http.client.jackson2;
    requires transitive com.mastfrog.acteur.auth;
    requires transitive com.mastfrog.url;

    // derived from com.restfb/restfb-2022.4.0 in com/restfb/restfb/2022.4.0/restfb-2022.4.0.pom
    requires transitive com.restfb.restfb;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.scribe/scribe-1.3.7 in org/scribe/scribe/1.3.7/scribe-1.3.7.pom
    requires transitive org.scribe.scribe;

}
