// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.google.auth {
    exports com.mastfrog.acteur.google.auth;

    // derived from com.google.http-client/google-http-client-jackson2-1.41.7 in com/google/http-client/google-http-client-jackson2/1.41.7/google-http-client-jackson2-1.41.7.pom
    requires transitive com.google.api.client.json.jackson2;

    // Sibling com.mastfrog/acteur-auth-3.0.0-dev
    requires com.mastfrog.acteur.auth;

    // Transitive detected by source scan
    requires com.mastfrog.acteur.deprecated;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Sibling com.mastfrog/url-3.0.0-dev
    requires com.mastfrog.url;

    // derived from com.google.api-client/google-api-client-1.32.2 in com/google/api-client/google-api-client/1.32.2/google-api-client-1.32.2.pom
    requires transitive google.api.client;

}
