open module com.mastfrog.acteur.google.auth {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.google.auth;

    // derived from com.google.api-client/google-api-client-1.32.2 in com/google/api-client/google-api-client/1.32.2/google-api-client-1.32.2.pom
    requires transitive com.google.api.client.google.api.client;

    // derived from com.google.http-client/google-http-client-jackson2-1.41.7 in com/google/http-client/google-http-client-jackson2/1.41.7/google-http-client-jackson2-1.41.7.pom
    requires transitive com.google.http.client.google.http.client.jackson2;
    requires transitive com.mastfrog.acteur.auth;
    requires transitive com.mastfrog.url;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
