open module com.mastfrog.acteur.linkedin {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.linkedin;
    requires transitive com.mastfrog.acteur.auth;
    requires transitive com.mastfrog.netty.http.client;
    requires transitive com.mastfrog.url;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
