// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.linkedin {
    exports com.mastfrog.acteur.linkedin;

    // Sibling com.mastfrog/acteur-auth-3.0.0-dev
    requires com.mastfrog.acteur.auth;

    // Transitive detected by source scan
    requires com.mastfrog.acteur.deprecated;

    // Sibling com.mastfrog/netty-http-client-3.0.0-dev
    requires com.mastfrog.netty.http.client;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Sibling com.mastfrog/url-3.0.0-dev
    requires com.mastfrog.url;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.util.function;

}
